name: Docker Publish

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.alex48406 }}
          password: ${{ secrets.J6!kW9sZz }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourusername/yourimage:latest
